apiVersion: v1
kind: Service
metadata:
  name: notifications-api
  labels:
    app: notifications-api
spec:
  selector:
    app: notifications-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
  labels:
    app: notifications-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: notifications-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:            
            - name: RABBITMQ_QUEUE
              value: "products_notification"
            - name: RABBITMQ_EXCHANGE
              value: "products_exchange"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
