apiVersion: v1
kind: Service
metadata:
  name: products-api
spec:
  selector:
    app: products-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  labels:
    app: products-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:      
        - name:  products-api
          image: products-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USERNAME
              value: root  
            - name: MYSQL_PASSWORD
              value: toor            
            - name: MONGO_HOST
              value: mongo         
            - name: MONGO_DATABASE
              value: my_database
            - name: MONGO_PORT
              value: "27017"
